// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.20.0
// source: system/v1/resource.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// HardwareConfigServiceClient is the client API for HardwareConfigService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type HardwareConfigServiceClient interface {
	// 获取所有资源配置
	ListResourceConfigs(ctx context.Context, in *ListResourceConfigsRequest, opts ...grpc.CallOption) (*ListResourceConfigsResponse, error)
	// 获取资源配置
	GetResourceConfig(ctx context.Context, in *GetResourceConfigRequest, opts ...grpc.CallOption) (*Resource, error)
	// 更新资源配置
	UpdateResourceConfig(ctx context.Context, in *UpdateResourceConfigRequest, opts ...grpc.CallOption) (*Resource, error)
}

type hardwareConfigServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewHardwareConfigServiceClient(cc grpc.ClientConnInterface) HardwareConfigServiceClient {
	return &hardwareConfigServiceClient{cc}
}

func (c *hardwareConfigServiceClient) ListResourceConfigs(ctx context.Context, in *ListResourceConfigsRequest, opts ...grpc.CallOption) (*ListResourceConfigsResponse, error) {
	out := new(ListResourceConfigsResponse)
	err := c.cc.Invoke(ctx, "/xtopus.api.system.v1.HardwareConfigService/ListResourceConfigs", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hardwareConfigServiceClient) GetResourceConfig(ctx context.Context, in *GetResourceConfigRequest, opts ...grpc.CallOption) (*Resource, error) {
	out := new(Resource)
	err := c.cc.Invoke(ctx, "/xtopus.api.system.v1.HardwareConfigService/GetResourceConfig", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hardwareConfigServiceClient) UpdateResourceConfig(ctx context.Context, in *UpdateResourceConfigRequest, opts ...grpc.CallOption) (*Resource, error) {
	out := new(Resource)
	err := c.cc.Invoke(ctx, "/xtopus.api.system.v1.HardwareConfigService/UpdateResourceConfig", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HardwareConfigServiceServer is the server API for HardwareConfigService service.
// All implementations must embed UnimplementedHardwareConfigServiceServer
// for forward compatibility
type HardwareConfigServiceServer interface {
	// 获取所有资源配置
	ListResourceConfigs(context.Context, *ListResourceConfigsRequest) (*ListResourceConfigsResponse, error)
	// 获取资源配置
	GetResourceConfig(context.Context, *GetResourceConfigRequest) (*Resource, error)
	// 更新资源配置
	UpdateResourceConfig(context.Context, *UpdateResourceConfigRequest) (*Resource, error)
	mustEmbedUnimplementedHardwareConfigServiceServer()
}

// UnimplementedHardwareConfigServiceServer must be embedded to have forward compatible implementations.
type UnimplementedHardwareConfigServiceServer struct {
}

func (UnimplementedHardwareConfigServiceServer) ListResourceConfigs(context.Context, *ListResourceConfigsRequest) (*ListResourceConfigsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListResourceConfigs not implemented")
}
func (UnimplementedHardwareConfigServiceServer) GetResourceConfig(context.Context, *GetResourceConfigRequest) (*Resource, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetResourceConfig not implemented")
}
func (UnimplementedHardwareConfigServiceServer) UpdateResourceConfig(context.Context, *UpdateResourceConfigRequest) (*Resource, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateResourceConfig not implemented")
}
func (UnimplementedHardwareConfigServiceServer) mustEmbedUnimplementedHardwareConfigServiceServer() {}

// UnsafeHardwareConfigServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to HardwareConfigServiceServer will
// result in compilation errors.
type UnsafeHardwareConfigServiceServer interface {
	mustEmbedUnimplementedHardwareConfigServiceServer()
}

func RegisterHardwareConfigServiceServer(s grpc.ServiceRegistrar, srv HardwareConfigServiceServer) {
	s.RegisterService(&HardwareConfigService_ServiceDesc, srv)
}

func _HardwareConfigService_ListResourceConfigs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListResourceConfigsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HardwareConfigServiceServer).ListResourceConfigs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/xtopus.api.system.v1.HardwareConfigService/ListResourceConfigs",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HardwareConfigServiceServer).ListResourceConfigs(ctx, req.(*ListResourceConfigsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HardwareConfigService_GetResourceConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetResourceConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HardwareConfigServiceServer).GetResourceConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/xtopus.api.system.v1.HardwareConfigService/GetResourceConfig",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HardwareConfigServiceServer).GetResourceConfig(ctx, req.(*GetResourceConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HardwareConfigService_UpdateResourceConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateResourceConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HardwareConfigServiceServer).UpdateResourceConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/xtopus.api.system.v1.HardwareConfigService/UpdateResourceConfig",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HardwareConfigServiceServer).UpdateResourceConfig(ctx, req.(*UpdateResourceConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// HardwareConfigService_ServiceDesc is the grpc.ServiceDesc for HardwareConfigService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var HardwareConfigService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "xtopus.api.system.v1.HardwareConfigService",
	HandlerType: (*HardwareConfigServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListResourceConfigs",
			Handler:    _HardwareConfigService_ListResourceConfigs_Handler,
		},
		{
			MethodName: "GetResourceConfig",
			Handler:    _HardwareConfigService_GetResourceConfig_Handler,
		},
		{
			MethodName: "UpdateResourceConfig",
			Handler:    _HardwareConfigService_UpdateResourceConfig_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "system/v1/resource.proto",
}
