// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.12.4
// source: system/v1/resource.proto

package v1

import (
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ResourceConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ApiVersion    string                 `protobuf:"bytes,1,opt,name=api_version,json=apiVersion,proto3" json:"api_version,omitempty"`
	Kind          string                 `protobuf:"bytes,2,opt,name=kind,proto3" json:"kind,omitempty"`
	Metadata      *Metadata              `protobuf:"bytes,3,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Spec          string                 `protobuf:"bytes,4,opt,name=spec,proto3" json:"spec,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResourceConfig) Reset() {
	*x = ResourceConfig{}
	mi := &file_system_v1_resource_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourceConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceConfig) ProtoMessage() {}

func (x *ResourceConfig) ProtoReflect() protoreflect.Message {
	mi := &file_system_v1_resource_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceConfig.ProtoReflect.Descriptor instead.
func (*ResourceConfig) Descriptor() ([]byte, []int) {
	return file_system_v1_resource_proto_rawDescGZIP(), []int{0}
}

func (x *ResourceConfig) GetApiVersion() string {
	if x != nil {
		return x.ApiVersion
	}
	return ""
}

func (x *ResourceConfig) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *ResourceConfig) GetMetadata() *Metadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *ResourceConfig) GetSpec() string {
	if x != nil {
		return x.Spec
	}
	return ""
}

type Metadata struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Name            string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	ResourceVersion string                 `protobuf:"bytes,2,opt,name=resource_version,json=resourceVersion,proto3" json:"resource_version,omitempty"`
	Generation      int32                  `protobuf:"varint,3,opt,name=generation,proto3" json:"generation,omitempty"`
	CreationTime    string                 `protobuf:"bytes,4,opt,name=creation_time,json=creationTime,proto3" json:"creation_time,omitempty"`
	DeletionTime    string                 `protobuf:"bytes,5,opt,name=deletion_time,json=deletionTime,proto3" json:"deletion_time,omitempty"`
	Labels          map[string]string      `protobuf:"bytes,6,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Annotations     map[string]string      `protobuf:"bytes,7,rep,name=annotations,proto3" json:"annotations,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Metadata) Reset() {
	*x = Metadata{}
	mi := &file_system_v1_resource_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Metadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Metadata) ProtoMessage() {}

func (x *Metadata) ProtoReflect() protoreflect.Message {
	mi := &file_system_v1_resource_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Metadata.ProtoReflect.Descriptor instead.
func (*Metadata) Descriptor() ([]byte, []int) {
	return file_system_v1_resource_proto_rawDescGZIP(), []int{1}
}

func (x *Metadata) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Metadata) GetResourceVersion() string {
	if x != nil {
		return x.ResourceVersion
	}
	return ""
}

func (x *Metadata) GetGeneration() int32 {
	if x != nil {
		return x.Generation
	}
	return 0
}

func (x *Metadata) GetCreationTime() string {
	if x != nil {
		return x.CreationTime
	}
	return ""
}

func (x *Metadata) GetDeletionTime() string {
	if x != nil {
		return x.DeletionTime
	}
	return ""
}

func (x *Metadata) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *Metadata) GetAnnotations() map[string]string {
	if x != nil {
		return x.Annotations
	}
	return nil
}

type ResourceStatus struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 当前阶段
	Phase string `protobuf:"bytes,1,opt,name=phase,proto3" json:"phase,omitempty"`
	// 原因
	Reason string `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	// 消息
	Message string `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	// 最后同步时间
	LastReconcileTime *timestamp.Timestamp `protobuf:"bytes,4,opt,name=last_reconcile_time,json=lastReconcileTime,proto3" json:"last_reconcile_time,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ResourceStatus) Reset() {
	*x = ResourceStatus{}
	mi := &file_system_v1_resource_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourceStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceStatus) ProtoMessage() {}

func (x *ResourceStatus) ProtoReflect() protoreflect.Message {
	mi := &file_system_v1_resource_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceStatus.ProtoReflect.Descriptor instead.
func (*ResourceStatus) Descriptor() ([]byte, []int) {
	return file_system_v1_resource_proto_rawDescGZIP(), []int{2}
}

func (x *ResourceStatus) GetPhase() string {
	if x != nil {
		return x.Phase
	}
	return ""
}

func (x *ResourceStatus) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *ResourceStatus) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ResourceStatus) GetLastReconcileTime() *timestamp.Timestamp {
	if x != nil {
		return x.LastReconcileTime
	}
	return nil
}

type Resource struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Config          *ResourceConfig        `protobuf:"bytes,1,opt,name=config,proto3" json:"config,omitempty"`
	EffectiveConfig *ResourceConfig        `protobuf:"bytes,2,opt,name=effective_config,json=effectiveConfig,proto3" json:"effective_config,omitempty"`
	Status          *ResourceStatus        `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Resource) Reset() {
	*x = Resource{}
	mi := &file_system_v1_resource_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Resource) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Resource) ProtoMessage() {}

func (x *Resource) ProtoReflect() protoreflect.Message {
	mi := &file_system_v1_resource_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Resource.ProtoReflect.Descriptor instead.
func (*Resource) Descriptor() ([]byte, []int) {
	return file_system_v1_resource_proto_rawDescGZIP(), []int{3}
}

func (x *Resource) GetConfig() *ResourceConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *Resource) GetEffectiveConfig() *ResourceConfig {
	if x != nil {
		return x.EffectiveConfig
	}
	return nil
}

func (x *Resource) GetStatus() *ResourceStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

type ListResourceConfigsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Kind          string                 `protobuf:"bytes,1,opt,name=kind,proto3" json:"kind,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListResourceConfigsRequest) Reset() {
	*x = ListResourceConfigsRequest{}
	mi := &file_system_v1_resource_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListResourceConfigsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListResourceConfigsRequest) ProtoMessage() {}

func (x *ListResourceConfigsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_system_v1_resource_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListResourceConfigsRequest.ProtoReflect.Descriptor instead.
func (*ListResourceConfigsRequest) Descriptor() ([]byte, []int) {
	return file_system_v1_resource_proto_rawDescGZIP(), []int{4}
}

func (x *ListResourceConfigsRequest) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

type ListResourceConfigsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Resources     []*Resource            `protobuf:"bytes,1,rep,name=resources,proto3" json:"resources,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListResourceConfigsResponse) Reset() {
	*x = ListResourceConfigsResponse{}
	mi := &file_system_v1_resource_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListResourceConfigsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListResourceConfigsResponse) ProtoMessage() {}

func (x *ListResourceConfigsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_system_v1_resource_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListResourceConfigsResponse.ProtoReflect.Descriptor instead.
func (*ListResourceConfigsResponse) Descriptor() ([]byte, []int) {
	return file_system_v1_resource_proto_rawDescGZIP(), []int{5}
}

func (x *ListResourceConfigsResponse) GetResources() []*Resource {
	if x != nil {
		return x.Resources
	}
	return nil
}

type GetResourceConfigRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetResourceConfigRequest) Reset() {
	*x = GetResourceConfigRequest{}
	mi := &file_system_v1_resource_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetResourceConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetResourceConfigRequest) ProtoMessage() {}

func (x *GetResourceConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_system_v1_resource_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetResourceConfigRequest.ProtoReflect.Descriptor instead.
func (*GetResourceConfigRequest) Descriptor() ([]byte, []int) {
	return file_system_v1_resource_proto_rawDescGZIP(), []int{6}
}

func (x *GetResourceConfigRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type UpdateResourceConfigRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Resource      *Resource              `protobuf:"bytes,2,opt,name=resource,proto3" json:"resource,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateResourceConfigRequest) Reset() {
	*x = UpdateResourceConfigRequest{}
	mi := &file_system_v1_resource_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateResourceConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateResourceConfigRequest) ProtoMessage() {}

func (x *UpdateResourceConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_system_v1_resource_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateResourceConfigRequest.ProtoReflect.Descriptor instead.
func (*UpdateResourceConfigRequest) Descriptor() ([]byte, []int) {
	return file_system_v1_resource_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateResourceConfigRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateResourceConfigRequest) GetResource() *Resource {
	if x != nil {
		return x.Resource
	}
	return nil
}

var File_system_v1_resource_proto protoreflect.FileDescriptor

const file_system_v1_resource_proto_rawDesc = "" +
	"\n" +
	"\x18system/v1/resource.proto\x12\x14xtopus.api.system.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1cgoogle/api/annotations.proto\"\x95\x01\n" +
	"\x0eResourceConfig\x12\x1f\n" +
	"\vapi_version\x18\x01 \x01(\tR\n" +
	"apiVersion\x12\x12\n" +
	"\x04kind\x18\x02 \x01(\tR\x04kind\x12:\n" +
	"\bmetadata\x18\x03 \x01(\v2\x1e.xtopus.api.system.v1.MetadataR\bmetadata\x12\x12\n" +
	"\x04spec\x18\x04 \x01(\tR\x04spec\"\xc5\x03\n" +
	"\bMetadata\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12)\n" +
	"\x10resource_version\x18\x02 \x01(\tR\x0fresourceVersion\x12\x1e\n" +
	"\n" +
	"generation\x18\x03 \x01(\x05R\n" +
	"generation\x12#\n" +
	"\rcreation_time\x18\x04 \x01(\tR\fcreationTime\x12#\n" +
	"\rdeletion_time\x18\x05 \x01(\tR\fdeletionTime\x12B\n" +
	"\x06labels\x18\x06 \x03(\v2*.xtopus.api.system.v1.Metadata.LabelsEntryR\x06labels\x12Q\n" +
	"\vannotations\x18\a \x03(\v2/.xtopus.api.system.v1.Metadata.AnnotationsEntryR\vannotations\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a>\n" +
	"\x10AnnotationsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xa4\x01\n" +
	"\x0eResourceStatus\x12\x14\n" +
	"\x05phase\x18\x01 \x01(\tR\x05phase\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12J\n" +
	"\x13last_reconcile_time\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\x11lastReconcileTime\"\xd7\x01\n" +
	"\bResource\x12<\n" +
	"\x06config\x18\x01 \x01(\v2$.xtopus.api.system.v1.ResourceConfigR\x06config\x12O\n" +
	"\x10effective_config\x18\x02 \x01(\v2$.xtopus.api.system.v1.ResourceConfigR\x0feffectiveConfig\x12<\n" +
	"\x06status\x18\x03 \x01(\v2$.xtopus.api.system.v1.ResourceStatusR\x06status\"0\n" +
	"\x1aListResourceConfigsRequest\x12\x12\n" +
	"\x04kind\x18\x01 \x01(\tR\x04kind\"[\n" +
	"\x1bListResourceConfigsResponse\x12<\n" +
	"\tresources\x18\x01 \x03(\v2\x1e.xtopus.api.system.v1.ResourceR\tresources\".\n" +
	"\x18GetResourceConfigRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"m\n" +
	"\x1bUpdateResourceConfigRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12:\n" +
	"\bresource\x18\x02 \x01(\v2\x1e.xtopus.api.system.v1.ResourceR\bresource2\xbc\x03\n" +
	"\x15HardwareConfigService\x12\x91\x01\n" +
	"\x13ListResourceConfigs\x120.xtopus.api.system.v1.ListResourceConfigsRequest\x1a1.xtopus.api.system.v1.ListResourceConfigsResponse\"\x15\x82\xd3\xe4\x93\x02\x0f\x12\r/v1/resources\x12\x81\x01\n" +
	"\x11GetResourceConfig\x12..xtopus.api.system.v1.GetResourceConfigRequest\x1a\x1e.xtopus.api.system.v1.Resource\"\x1c\x82\xd3\xe4\x93\x02\x16\x12\x14/v1/resources/{name}\x12\x8a\x01\n" +
	"\x14UpdateResourceConfig\x121.xtopus.api.system.v1.UpdateResourceConfigRequest\x1a\x1e.xtopus.api.system.v1.Resource\"\x1f\x82\xd3\xe4\x93\x02\x19:\x01*\x1a\x14/v1/resources/{name}B,Z*go.xbrother.com/nix-operator/api/system/v1b\x06proto3"

var (
	file_system_v1_resource_proto_rawDescOnce sync.Once
	file_system_v1_resource_proto_rawDescData []byte
)

func file_system_v1_resource_proto_rawDescGZIP() []byte {
	file_system_v1_resource_proto_rawDescOnce.Do(func() {
		file_system_v1_resource_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_system_v1_resource_proto_rawDesc), len(file_system_v1_resource_proto_rawDesc)))
	})
	return file_system_v1_resource_proto_rawDescData
}

var file_system_v1_resource_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_system_v1_resource_proto_goTypes = []any{
	(*ResourceConfig)(nil),              // 0: xtopus.api.system.v1.ResourceConfig
	(*Metadata)(nil),                    // 1: xtopus.api.system.v1.Metadata
	(*ResourceStatus)(nil),              // 2: xtopus.api.system.v1.ResourceStatus
	(*Resource)(nil),                    // 3: xtopus.api.system.v1.Resource
	(*ListResourceConfigsRequest)(nil),  // 4: xtopus.api.system.v1.ListResourceConfigsRequest
	(*ListResourceConfigsResponse)(nil), // 5: xtopus.api.system.v1.ListResourceConfigsResponse
	(*GetResourceConfigRequest)(nil),    // 6: xtopus.api.system.v1.GetResourceConfigRequest
	(*UpdateResourceConfigRequest)(nil), // 7: xtopus.api.system.v1.UpdateResourceConfigRequest
	nil,                                 // 8: xtopus.api.system.v1.Metadata.LabelsEntry
	nil,                                 // 9: xtopus.api.system.v1.Metadata.AnnotationsEntry
	(*timestamp.Timestamp)(nil),         // 10: google.protobuf.Timestamp
}
var file_system_v1_resource_proto_depIdxs = []int32{
	1,  // 0: xtopus.api.system.v1.ResourceConfig.metadata:type_name -> xtopus.api.system.v1.Metadata
	8,  // 1: xtopus.api.system.v1.Metadata.labels:type_name -> xtopus.api.system.v1.Metadata.LabelsEntry
	9,  // 2: xtopus.api.system.v1.Metadata.annotations:type_name -> xtopus.api.system.v1.Metadata.AnnotationsEntry
	10, // 3: xtopus.api.system.v1.ResourceStatus.last_reconcile_time:type_name -> google.protobuf.Timestamp
	0,  // 4: xtopus.api.system.v1.Resource.config:type_name -> xtopus.api.system.v1.ResourceConfig
	0,  // 5: xtopus.api.system.v1.Resource.effective_config:type_name -> xtopus.api.system.v1.ResourceConfig
	2,  // 6: xtopus.api.system.v1.Resource.status:type_name -> xtopus.api.system.v1.ResourceStatus
	3,  // 7: xtopus.api.system.v1.ListResourceConfigsResponse.resources:type_name -> xtopus.api.system.v1.Resource
	3,  // 8: xtopus.api.system.v1.UpdateResourceConfigRequest.resource:type_name -> xtopus.api.system.v1.Resource
	4,  // 9: xtopus.api.system.v1.HardwareConfigService.ListResourceConfigs:input_type -> xtopus.api.system.v1.ListResourceConfigsRequest
	6,  // 10: xtopus.api.system.v1.HardwareConfigService.GetResourceConfig:input_type -> xtopus.api.system.v1.GetResourceConfigRequest
	7,  // 11: xtopus.api.system.v1.HardwareConfigService.UpdateResourceConfig:input_type -> xtopus.api.system.v1.UpdateResourceConfigRequest
	5,  // 12: xtopus.api.system.v1.HardwareConfigService.ListResourceConfigs:output_type -> xtopus.api.system.v1.ListResourceConfigsResponse
	3,  // 13: xtopus.api.system.v1.HardwareConfigService.GetResourceConfig:output_type -> xtopus.api.system.v1.Resource
	3,  // 14: xtopus.api.system.v1.HardwareConfigService.UpdateResourceConfig:output_type -> xtopus.api.system.v1.Resource
	12, // [12:15] is the sub-list for method output_type
	9,  // [9:12] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_system_v1_resource_proto_init() }
func file_system_v1_resource_proto_init() {
	if File_system_v1_resource_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_system_v1_resource_proto_rawDesc), len(file_system_v1_resource_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_system_v1_resource_proto_goTypes,
		DependencyIndexes: file_system_v1_resource_proto_depIdxs,
		MessageInfos:      file_system_v1_resource_proto_msgTypes,
	}.Build()
	File_system_v1_resource_proto = out.File
	file_system_v1_resource_proto_goTypes = nil
	file_system_v1_resource_proto_depIdxs = nil
}
