// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.20.0
// source: system/v1/resource.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// SystemConfigServiceClient is the client API for SystemConfigService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SystemConfigServiceClient interface {
	// 获取所有资源配置
	ListResourceConfigs(ctx context.Context, in *ListResourceConfigsRequest, opts ...grpc.CallOption) (*ListResourceConfigsResponse, error)
	// 获取资源配置
	GetResourceConfig(ctx context.Context, in *GetResourceConfigRequest, opts ...grpc.CallOption) (*ResourceConfig, error)
	// 更新资源配置
	UpdateResourceConfig(ctx context.Context, in *UpdateResourceConfigRequest, opts ...grpc.CallOption) (*ResourceConfig, error)
	// 获取资源 JSON Schema
	GetResourceSchemas(ctx context.Context, in *GetResourceSchemasRequest, opts ...grpc.CallOption) (*GetResourceSchemasResponse, error)
	// 获取所有节点信息
	ListNodes(ctx context.Context, in *ListNodesRequest, opts ...grpc.CallOption) (*ListNodesResponse, error)
}

type systemConfigServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSystemConfigServiceClient(cc grpc.ClientConnInterface) SystemConfigServiceClient {
	return &systemConfigServiceClient{cc}
}

func (c *systemConfigServiceClient) ListResourceConfigs(ctx context.Context, in *ListResourceConfigsRequest, opts ...grpc.CallOption) (*ListResourceConfigsResponse, error) {
	out := new(ListResourceConfigsResponse)
	err := c.cc.Invoke(ctx, "/xtopus.api.system.v1.SystemConfigService/ListResourceConfigs", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *systemConfigServiceClient) GetResourceConfig(ctx context.Context, in *GetResourceConfigRequest, opts ...grpc.CallOption) (*ResourceConfig, error) {
	out := new(ResourceConfig)
	err := c.cc.Invoke(ctx, "/xtopus.api.system.v1.SystemConfigService/GetResourceConfig", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *systemConfigServiceClient) UpdateResourceConfig(ctx context.Context, in *UpdateResourceConfigRequest, opts ...grpc.CallOption) (*ResourceConfig, error) {
	out := new(ResourceConfig)
	err := c.cc.Invoke(ctx, "/xtopus.api.system.v1.SystemConfigService/UpdateResourceConfig", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *systemConfigServiceClient) GetResourceSchemas(ctx context.Context, in *GetResourceSchemasRequest, opts ...grpc.CallOption) (*GetResourceSchemasResponse, error) {
	out := new(GetResourceSchemasResponse)
	err := c.cc.Invoke(ctx, "/xtopus.api.system.v1.SystemConfigService/GetResourceSchemas", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *systemConfigServiceClient) ListNodes(ctx context.Context, in *ListNodesRequest, opts ...grpc.CallOption) (*ListNodesResponse, error) {
	out := new(ListNodesResponse)
	err := c.cc.Invoke(ctx, "/xtopus.api.system.v1.SystemConfigService/ListNodes", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SystemConfigServiceServer is the server API for SystemConfigService service.
// All implementations must embed UnimplementedSystemConfigServiceServer
// for forward compatibility
type SystemConfigServiceServer interface {
	// 获取所有资源配置
	ListResourceConfigs(context.Context, *ListResourceConfigsRequest) (*ListResourceConfigsResponse, error)
	// 获取资源配置
	GetResourceConfig(context.Context, *GetResourceConfigRequest) (*ResourceConfig, error)
	// 更新资源配置
	UpdateResourceConfig(context.Context, *UpdateResourceConfigRequest) (*ResourceConfig, error)
	// 获取资源 JSON Schema
	GetResourceSchemas(context.Context, *GetResourceSchemasRequest) (*GetResourceSchemasResponse, error)
	// 获取所有节点信息
	ListNodes(context.Context, *ListNodesRequest) (*ListNodesResponse, error)
	mustEmbedUnimplementedSystemConfigServiceServer()
}

// UnimplementedSystemConfigServiceServer must be embedded to have forward compatible implementations.
type UnimplementedSystemConfigServiceServer struct {
}

func (UnimplementedSystemConfigServiceServer) ListResourceConfigs(context.Context, *ListResourceConfigsRequest) (*ListResourceConfigsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListResourceConfigs not implemented")
}
func (UnimplementedSystemConfigServiceServer) GetResourceConfig(context.Context, *GetResourceConfigRequest) (*ResourceConfig, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetResourceConfig not implemented")
}
func (UnimplementedSystemConfigServiceServer) UpdateResourceConfig(context.Context, *UpdateResourceConfigRequest) (*ResourceConfig, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateResourceConfig not implemented")
}
func (UnimplementedSystemConfigServiceServer) GetResourceSchemas(context.Context, *GetResourceSchemasRequest) (*GetResourceSchemasResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetResourceSchemas not implemented")
}
func (UnimplementedSystemConfigServiceServer) ListNodes(context.Context, *ListNodesRequest) (*ListNodesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListNodes not implemented")
}
func (UnimplementedSystemConfigServiceServer) mustEmbedUnimplementedSystemConfigServiceServer() {}

// UnsafeSystemConfigServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SystemConfigServiceServer will
// result in compilation errors.
type UnsafeSystemConfigServiceServer interface {
	mustEmbedUnimplementedSystemConfigServiceServer()
}

func RegisterSystemConfigServiceServer(s grpc.ServiceRegistrar, srv SystemConfigServiceServer) {
	s.RegisterService(&SystemConfigService_ServiceDesc, srv)
}

func _SystemConfigService_ListResourceConfigs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListResourceConfigsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SystemConfigServiceServer).ListResourceConfigs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/xtopus.api.system.v1.SystemConfigService/ListResourceConfigs",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SystemConfigServiceServer).ListResourceConfigs(ctx, req.(*ListResourceConfigsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SystemConfigService_GetResourceConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetResourceConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SystemConfigServiceServer).GetResourceConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/xtopus.api.system.v1.SystemConfigService/GetResourceConfig",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SystemConfigServiceServer).GetResourceConfig(ctx, req.(*GetResourceConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SystemConfigService_UpdateResourceConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateResourceConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SystemConfigServiceServer).UpdateResourceConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/xtopus.api.system.v1.SystemConfigService/UpdateResourceConfig",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SystemConfigServiceServer).UpdateResourceConfig(ctx, req.(*UpdateResourceConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SystemConfigService_GetResourceSchemas_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetResourceSchemasRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SystemConfigServiceServer).GetResourceSchemas(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/xtopus.api.system.v1.SystemConfigService/GetResourceSchemas",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SystemConfigServiceServer).GetResourceSchemas(ctx, req.(*GetResourceSchemasRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SystemConfigService_ListNodes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListNodesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SystemConfigServiceServer).ListNodes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/xtopus.api.system.v1.SystemConfigService/ListNodes",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SystemConfigServiceServer).ListNodes(ctx, req.(*ListNodesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SystemConfigService_ServiceDesc is the grpc.ServiceDesc for SystemConfigService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SystemConfigService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "xtopus.api.system.v1.SystemConfigService",
	HandlerType: (*SystemConfigServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListResourceConfigs",
			Handler:    _SystemConfigService_ListResourceConfigs_Handler,
		},
		{
			MethodName: "GetResourceConfig",
			Handler:    _SystemConfigService_GetResourceConfig_Handler,
		},
		{
			MethodName: "UpdateResourceConfig",
			Handler:    _SystemConfigService_UpdateResourceConfig_Handler,
		},
		{
			MethodName: "GetResourceSchemas",
			Handler:    _SystemConfigService_GetResourceSchemas_Handler,
		},
		{
			MethodName: "ListNodes",
			Handler:    _SystemConfigService_ListNodes_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "system/v1/resource.proto",
}
