// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.20.0
// source: system/v1/system.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// SystemServiceClient is the client API for SystemService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SystemServiceClient interface {
	// 获取所有网卡
	ListNetworkInterfaces(ctx context.Context, in *ListNetworkInterfacesRequest, opts ...grpc.CallOption) (*ListNetworkInterfacesResponse, error)
	// 获取单个网络接口
	GetNetworkInterface(ctx context.Context, in *GetNetworkInterfaceRequest, opts ...grpc.CallOption) (*GetNetworkInterfaceResponse, error)
	// 更新网络接口配置
	UpdateNetworkInterface(ctx context.Context, in *UpdateNetworkInterfaceRequest, opts ...grpc.CallOption) (*UpdateNetworkInterfaceResponse, error)
	// 获取所有hosts配置
	ListHostsConfigurations(ctx context.Context, in *ListHostsConfigurationsRequest, opts ...grpc.CallOption) (*ListHostsConfigurationsResponse, error)
	// 更新hosts配置
	UpdateHostsConfiguration(ctx context.Context, in *UpdateHostsConfigurationRequest, opts ...grpc.CallOption) (*UpdateHostsConfigurationResponse, error)
}

type systemServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSystemServiceClient(cc grpc.ClientConnInterface) SystemServiceClient {
	return &systemServiceClient{cc}
}

func (c *systemServiceClient) ListNetworkInterfaces(ctx context.Context, in *ListNetworkInterfacesRequest, opts ...grpc.CallOption) (*ListNetworkInterfacesResponse, error) {
	out := new(ListNetworkInterfacesResponse)
	err := c.cc.Invoke(ctx, "/xtopus.api.system.v1.SystemService/ListNetworkInterfaces", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *systemServiceClient) GetNetworkInterface(ctx context.Context, in *GetNetworkInterfaceRequest, opts ...grpc.CallOption) (*GetNetworkInterfaceResponse, error) {
	out := new(GetNetworkInterfaceResponse)
	err := c.cc.Invoke(ctx, "/xtopus.api.system.v1.SystemService/GetNetworkInterface", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *systemServiceClient) UpdateNetworkInterface(ctx context.Context, in *UpdateNetworkInterfaceRequest, opts ...grpc.CallOption) (*UpdateNetworkInterfaceResponse, error) {
	out := new(UpdateNetworkInterfaceResponse)
	err := c.cc.Invoke(ctx, "/xtopus.api.system.v1.SystemService/UpdateNetworkInterface", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *systemServiceClient) ListHostsConfigurations(ctx context.Context, in *ListHostsConfigurationsRequest, opts ...grpc.CallOption) (*ListHostsConfigurationsResponse, error) {
	out := new(ListHostsConfigurationsResponse)
	err := c.cc.Invoke(ctx, "/xtopus.api.system.v1.SystemService/ListHostsConfigurations", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *systemServiceClient) UpdateHostsConfiguration(ctx context.Context, in *UpdateHostsConfigurationRequest, opts ...grpc.CallOption) (*UpdateHostsConfigurationResponse, error) {
	out := new(UpdateHostsConfigurationResponse)
	err := c.cc.Invoke(ctx, "/xtopus.api.system.v1.SystemService/UpdateHostsConfiguration", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SystemServiceServer is the server API for SystemService service.
// All implementations must embed UnimplementedSystemServiceServer
// for forward compatibility
type SystemServiceServer interface {
	// 获取所有网卡
	ListNetworkInterfaces(context.Context, *ListNetworkInterfacesRequest) (*ListNetworkInterfacesResponse, error)
	// 获取单个网络接口
	GetNetworkInterface(context.Context, *GetNetworkInterfaceRequest) (*GetNetworkInterfaceResponse, error)
	// 更新网络接口配置
	UpdateNetworkInterface(context.Context, *UpdateNetworkInterfaceRequest) (*UpdateNetworkInterfaceResponse, error)
	// 获取所有hosts配置
	ListHostsConfigurations(context.Context, *ListHostsConfigurationsRequest) (*ListHostsConfigurationsResponse, error)
	// 更新hosts配置
	UpdateHostsConfiguration(context.Context, *UpdateHostsConfigurationRequest) (*UpdateHostsConfigurationResponse, error)
	mustEmbedUnimplementedSystemServiceServer()
}

// UnimplementedSystemServiceServer must be embedded to have forward compatible implementations.
type UnimplementedSystemServiceServer struct {
}

func (UnimplementedSystemServiceServer) ListNetworkInterfaces(context.Context, *ListNetworkInterfacesRequest) (*ListNetworkInterfacesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListNetworkInterfaces not implemented")
}
func (UnimplementedSystemServiceServer) GetNetworkInterface(context.Context, *GetNetworkInterfaceRequest) (*GetNetworkInterfaceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetNetworkInterface not implemented")
}
func (UnimplementedSystemServiceServer) UpdateNetworkInterface(context.Context, *UpdateNetworkInterfaceRequest) (*UpdateNetworkInterfaceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateNetworkInterface not implemented")
}
func (UnimplementedSystemServiceServer) ListHostsConfigurations(context.Context, *ListHostsConfigurationsRequest) (*ListHostsConfigurationsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListHostsConfigurations not implemented")
}
func (UnimplementedSystemServiceServer) UpdateHostsConfiguration(context.Context, *UpdateHostsConfigurationRequest) (*UpdateHostsConfigurationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateHostsConfiguration not implemented")
}
func (UnimplementedSystemServiceServer) mustEmbedUnimplementedSystemServiceServer() {}

// UnsafeSystemServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SystemServiceServer will
// result in compilation errors.
type UnsafeSystemServiceServer interface {
	mustEmbedUnimplementedSystemServiceServer()
}

func RegisterSystemServiceServer(s grpc.ServiceRegistrar, srv SystemServiceServer) {
	s.RegisterService(&SystemService_ServiceDesc, srv)
}

func _SystemService_ListNetworkInterfaces_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListNetworkInterfacesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SystemServiceServer).ListNetworkInterfaces(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/xtopus.api.system.v1.SystemService/ListNetworkInterfaces",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SystemServiceServer).ListNetworkInterfaces(ctx, req.(*ListNetworkInterfacesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SystemService_GetNetworkInterface_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetNetworkInterfaceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SystemServiceServer).GetNetworkInterface(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/xtopus.api.system.v1.SystemService/GetNetworkInterface",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SystemServiceServer).GetNetworkInterface(ctx, req.(*GetNetworkInterfaceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SystemService_UpdateNetworkInterface_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateNetworkInterfaceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SystemServiceServer).UpdateNetworkInterface(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/xtopus.api.system.v1.SystemService/UpdateNetworkInterface",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SystemServiceServer).UpdateNetworkInterface(ctx, req.(*UpdateNetworkInterfaceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SystemService_ListHostsConfigurations_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListHostsConfigurationsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SystemServiceServer).ListHostsConfigurations(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/xtopus.api.system.v1.SystemService/ListHostsConfigurations",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SystemServiceServer).ListHostsConfigurations(ctx, req.(*ListHostsConfigurationsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SystemService_UpdateHostsConfiguration_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateHostsConfigurationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SystemServiceServer).UpdateHostsConfiguration(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/xtopus.api.system.v1.SystemService/UpdateHostsConfiguration",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SystemServiceServer).UpdateHostsConfiguration(ctx, req.(*UpdateHostsConfigurationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SystemService_ServiceDesc is the grpc.ServiceDesc for SystemService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SystemService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "xtopus.api.system.v1.SystemService",
	HandlerType: (*SystemServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListNetworkInterfaces",
			Handler:    _SystemService_ListNetworkInterfaces_Handler,
		},
		{
			MethodName: "GetNetworkInterface",
			Handler:    _SystemService_GetNetworkInterface_Handler,
		},
		{
			MethodName: "UpdateNetworkInterface",
			Handler:    _SystemService_UpdateNetworkInterface_Handler,
		},
		{
			MethodName: "ListHostsConfigurations",
			Handler:    _SystemService_ListHostsConfigurations_Handler,
		},
		{
			MethodName: "UpdateHostsConfiguration",
			Handler:    _SystemService_UpdateHostsConfiguration_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "system/v1/system.proto",
}
