// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.12.4
// source: system/v1/system.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 接口状态
type InterfaceStatus int32

const (
	InterfaceStatus_Unknown InterfaceStatus = 0
	InterfaceStatus_Up      InterfaceStatus = 1
	InterfaceStatus_Down    InterfaceStatus = 2
)

// Enum value maps for InterfaceStatus.
var (
	InterfaceStatus_name = map[int32]string{
		0: "Unknown",
		1: "Up",
		2: "Down",
	}
	InterfaceStatus_value = map[string]int32{
		"Unknown": 0,
		"Up":      1,
		"Down":    2,
	}
)

func (x InterfaceStatus) Enum() *InterfaceStatus {
	p := new(InterfaceStatus)
	*p = x
	return p
}

func (x InterfaceStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (InterfaceStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_system_v1_system_proto_enumTypes[0].Descriptor()
}

func (InterfaceStatus) Type() protoreflect.EnumType {
	return &file_system_v1_system_proto_enumTypes[0]
}

func (x InterfaceStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use InterfaceStatus.Descriptor instead.
func (InterfaceStatus) EnumDescriptor() ([]byte, []int) {
	return file_system_v1_system_proto_rawDescGZIP(), []int{0}
}

type ListNetworkInterfacesRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 是否只列出本地网卡
	LocalOnly     bool `protobuf:"varint,1,opt,name=local_only,json=localOnly,proto3" json:"local_only,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListNetworkInterfacesRequest) Reset() {
	*x = ListNetworkInterfacesRequest{}
	mi := &file_system_v1_system_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListNetworkInterfacesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListNetworkInterfacesRequest) ProtoMessage() {}

func (x *ListNetworkInterfacesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_system_v1_system_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListNetworkInterfacesRequest.ProtoReflect.Descriptor instead.
func (*ListNetworkInterfacesRequest) Descriptor() ([]byte, []int) {
	return file_system_v1_system_proto_rawDescGZIP(), []int{0}
}

func (x *ListNetworkInterfacesRequest) GetLocalOnly() bool {
	if x != nil {
		return x.LocalOnly
	}
	return false
}

type ListNetworkInterfacesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Interfaces    []*NetworkInterface    `protobuf:"bytes,1,rep,name=interfaces,proto3" json:"interfaces,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListNetworkInterfacesResponse) Reset() {
	*x = ListNetworkInterfacesResponse{}
	mi := &file_system_v1_system_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListNetworkInterfacesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListNetworkInterfacesResponse) ProtoMessage() {}

func (x *ListNetworkInterfacesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_system_v1_system_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListNetworkInterfacesResponse.ProtoReflect.Descriptor instead.
func (*ListNetworkInterfacesResponse) Descriptor() ([]byte, []int) {
	return file_system_v1_system_proto_rawDescGZIP(), []int{1}
}

func (x *ListNetworkInterfacesResponse) GetInterfaces() []*NetworkInterface {
	if x != nil {
		return x.Interfaces
	}
	return nil
}

// 网络接口配置
type NetworkInterface struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 节点选择器
	NodeSelector *NodeSelector `protobuf:"bytes,1,opt,name=node_selector,json=nodeSelector,proto3" json:"node_selector,omitempty"`
	// 接口名称，如 eth0, ens33
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// IPv4 配置
	Ipv4 *IPv4Config `protobuf:"bytes,3,opt,name=ipv4,proto3" json:"ipv4,omitempty"`
	// IPv6 配置
	Ipv6 *IPv6Config `protobuf:"bytes,4,opt,name=ipv6,proto3" json:"ipv6,omitempty"`
	// MTU 大小
	Mtu int32 `protobuf:"varint,5,opt,name=mtu,proto3" json:"mtu,omitempty"`
	// MAC 地址
	MacAddress string `protobuf:"bytes,6,opt,name=mac_address,json=macAddress,proto3" json:"mac_address,omitempty"`
	// 接口状态
	Status        InterfaceStatus `protobuf:"varint,7,opt,name=status,proto3,enum=xtopus.api.system.v1.InterfaceStatus" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NetworkInterface) Reset() {
	*x = NetworkInterface{}
	mi := &file_system_v1_system_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NetworkInterface) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetworkInterface) ProtoMessage() {}

func (x *NetworkInterface) ProtoReflect() protoreflect.Message {
	mi := &file_system_v1_system_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetworkInterface.ProtoReflect.Descriptor instead.
func (*NetworkInterface) Descriptor() ([]byte, []int) {
	return file_system_v1_system_proto_rawDescGZIP(), []int{2}
}

func (x *NetworkInterface) GetNodeSelector() *NodeSelector {
	if x != nil {
		return x.NodeSelector
	}
	return nil
}

func (x *NetworkInterface) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *NetworkInterface) GetIpv4() *IPv4Config {
	if x != nil {
		return x.Ipv4
	}
	return nil
}

func (x *NetworkInterface) GetIpv6() *IPv6Config {
	if x != nil {
		return x.Ipv6
	}
	return nil
}

func (x *NetworkInterface) GetMtu() int32 {
	if x != nil {
		return x.Mtu
	}
	return 0
}

func (x *NetworkInterface) GetMacAddress() string {
	if x != nil {
		return x.MacAddress
	}
	return ""
}

func (x *NetworkInterface) GetStatus() InterfaceStatus {
	if x != nil {
		return x.Status
	}
	return InterfaceStatus_Unknown
}

// IPv4 配置
type IPv4Config struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// IP 地址和子网掩码，如 192.168.1.100/24
	Address string `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	// 网关地址
	Gateway string `protobuf:"bytes,2,opt,name=gateway,proto3" json:"gateway,omitempty"`
	// 是否启用 DHCP
	DhcpEnabled   bool `protobuf:"varint,3,opt,name=dhcp_enabled,json=dhcpEnabled,proto3" json:"dhcp_enabled,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IPv4Config) Reset() {
	*x = IPv4Config{}
	mi := &file_system_v1_system_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IPv4Config) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IPv4Config) ProtoMessage() {}

func (x *IPv4Config) ProtoReflect() protoreflect.Message {
	mi := &file_system_v1_system_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IPv4Config.ProtoReflect.Descriptor instead.
func (*IPv4Config) Descriptor() ([]byte, []int) {
	return file_system_v1_system_proto_rawDescGZIP(), []int{3}
}

func (x *IPv4Config) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *IPv4Config) GetGateway() string {
	if x != nil {
		return x.Gateway
	}
	return ""
}

func (x *IPv4Config) GetDhcpEnabled() bool {
	if x != nil {
		return x.DhcpEnabled
	}
	return false
}

// IPv6 配置
type IPv6Config struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// IPv6 地址和前缀长度，如 2001:db8::1/64
	Address string `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	// IPv6 网关
	Gateway string `protobuf:"bytes,2,opt,name=gateway,proto3" json:"gateway,omitempty"`
	// 是否启用 SLAAC
	SlaacEnabled  bool `protobuf:"varint,3,opt,name=slaac_enabled,json=slaacEnabled,proto3" json:"slaac_enabled,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IPv6Config) Reset() {
	*x = IPv6Config{}
	mi := &file_system_v1_system_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IPv6Config) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IPv6Config) ProtoMessage() {}

func (x *IPv6Config) ProtoReflect() protoreflect.Message {
	mi := &file_system_v1_system_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IPv6Config.ProtoReflect.Descriptor instead.
func (*IPv6Config) Descriptor() ([]byte, []int) {
	return file_system_v1_system_proto_rawDescGZIP(), []int{4}
}

func (x *IPv6Config) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *IPv6Config) GetGateway() string {
	if x != nil {
		return x.Gateway
	}
	return ""
}

func (x *IPv6Config) GetSlaacEnabled() bool {
	if x != nil {
		return x.SlaacEnabled
	}
	return false
}

// 节点选择器
type NodeSelector struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 主机名匹配
	Hostname string `protobuf:"bytes,1,opt,name=hostname,proto3" json:"hostname,omitempty"`
	// MAC 地址匹配
	MacAddress string `protobuf:"bytes,2,opt,name=mac_address,json=macAddress,proto3" json:"mac_address,omitempty"`
	// 标签选择器
	Labels        map[string]string `protobuf:"bytes,3,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeSelector) Reset() {
	*x = NodeSelector{}
	mi := &file_system_v1_system_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeSelector) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeSelector) ProtoMessage() {}

func (x *NodeSelector) ProtoReflect() protoreflect.Message {
	mi := &file_system_v1_system_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeSelector.ProtoReflect.Descriptor instead.
func (*NodeSelector) Descriptor() ([]byte, []int) {
	return file_system_v1_system_proto_rawDescGZIP(), []int{5}
}

func (x *NodeSelector) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *NodeSelector) GetMacAddress() string {
	if x != nil {
		return x.MacAddress
	}
	return ""
}

func (x *NodeSelector) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

var File_system_v1_system_proto protoreflect.FileDescriptor

const file_system_v1_system_proto_rawDesc = "" +
	"\n" +
	"\x16system/v1/system.proto\x12\x14xtopus.api.system.v1\x1a\x1cgoogle/api/annotations.proto\"=\n" +
	"\x1cListNetworkInterfacesRequest\x12\x1d\n" +
	"\n" +
	"local_only\x18\x01 \x01(\bR\tlocalOnly\"g\n" +
	"\x1dListNetworkInterfacesResponse\x12F\n" +
	"\n" +
	"interfaces\x18\x01 \x03(\v2&.xtopus.api.system.v1.NetworkInterfaceR\n" +
	"interfaces\"\xcd\x02\n" +
	"\x10NetworkInterface\x12G\n" +
	"\rnode_selector\x18\x01 \x01(\v2\".xtopus.api.system.v1.NodeSelectorR\fnodeSelector\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x124\n" +
	"\x04ipv4\x18\x03 \x01(\v2 .xtopus.api.system.v1.IPv4ConfigR\x04ipv4\x124\n" +
	"\x04ipv6\x18\x04 \x01(\v2 .xtopus.api.system.v1.IPv6ConfigR\x04ipv6\x12\x10\n" +
	"\x03mtu\x18\x05 \x01(\x05R\x03mtu\x12\x1f\n" +
	"\vmac_address\x18\x06 \x01(\tR\n" +
	"macAddress\x12=\n" +
	"\x06status\x18\a \x01(\x0e2%.xtopus.api.system.v1.InterfaceStatusR\x06status\"c\n" +
	"\n" +
	"IPv4Config\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\tR\aaddress\x12\x18\n" +
	"\agateway\x18\x02 \x01(\tR\agateway\x12!\n" +
	"\fdhcp_enabled\x18\x03 \x01(\bR\vdhcpEnabled\"e\n" +
	"\n" +
	"IPv6Config\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\tR\aaddress\x12\x18\n" +
	"\agateway\x18\x02 \x01(\tR\agateway\x12#\n" +
	"\rslaac_enabled\x18\x03 \x01(\bR\fslaacEnabled\"\xce\x01\n" +
	"\fNodeSelector\x12\x1a\n" +
	"\bhostname\x18\x01 \x01(\tR\bhostname\x12\x1f\n" +
	"\vmac_address\x18\x02 \x01(\tR\n" +
	"macAddress\x12F\n" +
	"\x06labels\x18\x03 \x03(\v2..xtopus.api.system.v1.NodeSelector.LabelsEntryR\x06labels\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01*0\n" +
	"\x0fInterfaceStatus\x12\v\n" +
	"\aUnknown\x10\x00\x12\x06\n" +
	"\x02Up\x10\x01\x12\b\n" +
	"\x04Down\x10\x022\xb2\x01\n" +
	"\rSystemService\x12\xa0\x01\n" +
	"\x15ListNetworkInterfaces\x122.xtopus.api.system.v1.ListNetworkInterfacesRequest\x1a3.xtopus.api.system.v1.ListNetworkInterfacesResponse\"\x1e\x82\xd3\xe4\x93\x02\x18\x12\x16/v1/network_interfacesB,Z*go.xbrother.com/nix-operator/api/system/v1b\x06proto3"

var (
	file_system_v1_system_proto_rawDescOnce sync.Once
	file_system_v1_system_proto_rawDescData []byte
)

func file_system_v1_system_proto_rawDescGZIP() []byte {
	file_system_v1_system_proto_rawDescOnce.Do(func() {
		file_system_v1_system_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_system_v1_system_proto_rawDesc), len(file_system_v1_system_proto_rawDesc)))
	})
	return file_system_v1_system_proto_rawDescData
}

var file_system_v1_system_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_system_v1_system_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_system_v1_system_proto_goTypes = []any{
	(InterfaceStatus)(0),                  // 0: xtopus.api.system.v1.InterfaceStatus
	(*ListNetworkInterfacesRequest)(nil),  // 1: xtopus.api.system.v1.ListNetworkInterfacesRequest
	(*ListNetworkInterfacesResponse)(nil), // 2: xtopus.api.system.v1.ListNetworkInterfacesResponse
	(*NetworkInterface)(nil),              // 3: xtopus.api.system.v1.NetworkInterface
	(*IPv4Config)(nil),                    // 4: xtopus.api.system.v1.IPv4Config
	(*IPv6Config)(nil),                    // 5: xtopus.api.system.v1.IPv6Config
	(*NodeSelector)(nil),                  // 6: xtopus.api.system.v1.NodeSelector
	nil,                                   // 7: xtopus.api.system.v1.NodeSelector.LabelsEntry
}
var file_system_v1_system_proto_depIdxs = []int32{
	3, // 0: xtopus.api.system.v1.ListNetworkInterfacesResponse.interfaces:type_name -> xtopus.api.system.v1.NetworkInterface
	6, // 1: xtopus.api.system.v1.NetworkInterface.node_selector:type_name -> xtopus.api.system.v1.NodeSelector
	4, // 2: xtopus.api.system.v1.NetworkInterface.ipv4:type_name -> xtopus.api.system.v1.IPv4Config
	5, // 3: xtopus.api.system.v1.NetworkInterface.ipv6:type_name -> xtopus.api.system.v1.IPv6Config
	0, // 4: xtopus.api.system.v1.NetworkInterface.status:type_name -> xtopus.api.system.v1.InterfaceStatus
	7, // 5: xtopus.api.system.v1.NodeSelector.labels:type_name -> xtopus.api.system.v1.NodeSelector.LabelsEntry
	1, // 6: xtopus.api.system.v1.SystemService.ListNetworkInterfaces:input_type -> xtopus.api.system.v1.ListNetworkInterfacesRequest
	2, // 7: xtopus.api.system.v1.SystemService.ListNetworkInterfaces:output_type -> xtopus.api.system.v1.ListNetworkInterfacesResponse
	7, // [7:8] is the sub-list for method output_type
	6, // [6:7] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_system_v1_system_proto_init() }
func file_system_v1_system_proto_init() {
	if File_system_v1_system_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_system_v1_system_proto_rawDesc), len(file_system_v1_system_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_system_v1_system_proto_goTypes,
		DependencyIndexes: file_system_v1_system_proto_depIdxs,
		EnumInfos:         file_system_v1_system_proto_enumTypes,
		MessageInfos:      file_system_v1_system_proto_msgTypes,
	}.Build()
	File_system_v1_system_proto = out.File
	file_system_v1_system_proto_goTypes = nil
	file_system_v1_system_proto_depIdxs = nil
}
