package domain

import (
	"time"

	systemv1 "go.xbrother.com/nix-operator/api/system/v1"
)

const (
	CommentHeader = "# Generated by nix-operator. DO NOT EDIT.\n"
)

// OSInfo 操作系统信息
type OSInfo struct {
	ID         string // 发行版ID，如 "ubuntu", "centos"
	VersionID  string // 发行版版本，如 "20.04", "7"
	KernelName string // 内核名称，如 "Linux"
	KernelVer  string // 内核版本
}

// Metadata 资源元数据
type Metadata struct {
	Name            string            `json:"name"`
	ResourceVersion string            `json:"resourceVersion"`
	Generation      int               `json:"generation"`
	CreationTime    time.Time         `json:"creationTime"`
	DeletionTime    *time.Time        `json:"deletionTime,omitempty"`
	Labels          map[string]string `json:"labels,omitempty"`
	Annotations     map[string]string `json:"annotations,omitempty"`
}

// MetadataCompat 兼容性元数据（用于与字符串时间格式的兼容）
type MetadataCompat struct {
	Name            string            `json:"name"`
	ResourceVersion string            `json:"resourceVersion"`
	Generation      int               `json:"generation"`
	CreationTime    string            `json:"creationTime"`
	DeletionTime    string            `json:"deletionTime"`
	Labels          map[string]string `json:"labels"`
	Annotations     map[string]string `json:"annotations"`
}

// // ResourceStatus 资源状态
// type ResourceStatus struct {
// 	Phase   string `json:"phase"`
// 	Reason  string `json:"reason,omitempty"`
// 	Message string `json:"message,omitempty"`
// }

// // ResourceConfig 资源配置
// type ResourceConfig struct {
// 	APIVersion string          `json:"apiVersion"`
// 	Kind       string          `json:"kind"`
// 	Metadata   Metadata        `json:"metadata"`
// 	Spec       json.RawMessage `json:"spec"`
// }

// // ResourceWithStatus 带状态的资源配置
// type ResourceWithStatus struct {
// 	Config          *systemv1.ResourceConfig
// 	EffectiveConfig *ResourceConfig
// 	Status          *ResourceStatus
// }

// ReconcileResult 调谐结果
type ReconcileResult struct {
	Effective *systemv1.ResourceConfig
	Status    *systemv1.ResourceStatus
}
