package linux

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
	"text/template"

	"go.xbrother.com/nix-operator/pkg/handlers/network/types"
)

// TestBondingSlaveConfigurationIntegration 集成测试：验证 bonding slave 配置生成
func TestBondingSlaveConfigurationIntegration(t *testing.T) {
	// 创建临时目录用于测试
	tempDir := t.TempDir()

	// 测试 bonding slave 接口配置
	t.Run("Generate Bonding Slave Configuration", func(t *testing.T) {
		// 创建 bonding slave 接口
		bondSlaveInterface := types.Interface{
			Name:        "ens36",
			IPv4Address: "192.168.1.100/24", // 在 bonding slave 中这些应该被忽略
			IPv6Address: "fd00::5688/64",
			IPv4Gateway: "192.168.1.1",
			IPv6Gateway: "fd00::1111",
			MTU:         1500,
			Nameservers: []string{"192.168.4.30"},
			BondingSlave: &types.BondingSlaveConfig{
				Enabled: true,
				Master:  "bond1",
			},
		}

		// 解析模板
		tmpl, err := template.New("nmconnection").Parse(nmConnectionTemplate)
		if err != nil {
			t.Fatalf("Failed to parse template: %v", err)
		}

		// 渲染模板
		var content strings.Builder
		if err := tmpl.Execute(&content, bondSlaveInterface); err != nil {
			t.Fatalf("Failed to execute template: %v", err)
		}

		generatedConfig := content.String()
		t.Logf("Generated bonding slave configuration:\n%s", generatedConfig)

		// 验证生成的配置包含正确的 bonding slave 设置
		if !strings.Contains(generatedConfig, "master=bond1") {
			t.Error("Generated config should contain 'master=bond1'")
		}

		if !strings.Contains(generatedConfig, "slave-type=bond") {
			t.Error("Generated config should contain 'slave-type=bond'")
		}

		if !strings.Contains(generatedConfig, "interface-name=ens36") {
			t.Error("Generated config should contain 'interface-name=ens36'")
		}

		// 验证 bonding slave 配置中不包含 IP 配置部分
		if strings.Contains(generatedConfig, "[ipv4]") {
			t.Error("Bonding slave config should not contain [ipv4] section")
		}

		if strings.Contains(generatedConfig, "[ipv6]") {
			t.Error("Bonding slave config should not contain [ipv6] section")
		}

		// 写入测试文件
		testConfigPath := filepath.Join(tempDir, "nix-operator-ens36.nmconnection")
		if err := os.WriteFile(testConfigPath, []byte(generatedConfig), 0600); err != nil {
			t.Fatalf("Failed to write test config: %v", err)
		}

		t.Logf("Bonding slave configuration written to: %s", testConfigPath)
	})

	// 测试普通接口配置
	t.Run("Generate Regular Interface Configuration", func(t *testing.T) {
		// 创建普通接口
		regularInterface := types.Interface{
			Name:        "ens33",
			IPv4Address: "192.168.34.104/24",
			IPv6Address: "fd00::5688/64",
			IPv4Gateway: "192.168.34.1",
			IPv6Gateway: "fd00::1111",
			MTU:         1500,
			Nameservers: []string{"192.168.4.31"},
			BondingSlave: nil, // 不是 bonding slave
		}

		// 解析模板
		tmpl, err := template.New("nmconnection").Parse(nmConnectionTemplate)
		if err != nil {
			t.Fatalf("Failed to parse template: %v", err)
		}

		// 渲染模板
		var content strings.Builder
		if err := tmpl.Execute(&content, regularInterface); err != nil {
			t.Fatalf("Failed to execute template: %v", err)
		}

		generatedConfig := content.String()
		t.Logf("Generated regular interface configuration:\n%s", generatedConfig)

		// 验证生成的配置包含正确的网络设置
		if !strings.Contains(generatedConfig, "interface-name=ens33") {
			t.Error("Generated config should contain 'interface-name=ens33'")
		}

		if !strings.Contains(generatedConfig, "addresses=192.168.34.104/24") {
			t.Error("Generated config should contain IPv4 address")
		}

		if !strings.Contains(generatedConfig, "gateway=192.168.34.1") {
			t.Error("Generated config should contain IPv4 gateway")
		}

		if !strings.Contains(generatedConfig, "dns=192.168.4.31") {
			t.Error("Generated config should contain DNS server")
		}

		// 验证普通接口配置包含 IP 配置部分
		if !strings.Contains(generatedConfig, "[ipv4]") {
			t.Error("Regular interface config should contain [ipv4] section")
		}

		if !strings.Contains(generatedConfig, "[ipv6]") {
			t.Error("Regular interface config should contain [ipv6] section")
		}

		// 验证不包含 bonding slave 相关配置
		if strings.Contains(generatedConfig, "master=") {
			t.Error("Regular interface config should not contain master configuration")
		}

		if strings.Contains(generatedConfig, "slave-type=bond") {
			t.Error("Regular interface config should not contain slave-type=bond")
		}

		// 写入测试文件
		testConfigPath := filepath.Join(tempDir, "nix-operator-ens33.nmconnection")
		if err := os.WriteFile(testConfigPath, []byte(generatedConfig), 0600); err != nil {
			t.Fatalf("Failed to write test config: %v", err)
		}

		t.Logf("Regular interface configuration written to: %s", testConfigPath)
	})
}

// TestBondingSlaveConfigurationComparison 对比测试：验证修复前后的差异
func TestBondingSlaveConfigurationComparison(t *testing.T) {
	// 模拟修复前的模板（没有 bonding slave 支持）
	oldTemplate := `# This file is generated by nix-operator
# Manual changes will be overwritten
[connection]
id=nix-operator-{{ .Name }}
type=ethernet
interface-name={{ .Name }}
autoconnect=true

[ethernet]
{{- if .MTU }}
mtu={{ .MTU }}
{{- end }}

[ipv4]
{{- if .IPv4Address }}
method=manual
addresses={{ .IPv4Address }}
{{- if .IPv4Gateway }}
gateway={{ .IPv4Gateway }}
{{- end }}
{{- else }}
method=auto
{{- end }}
{{- if .Nameservers }}
dns={{ range $i, $dns := .Nameservers }}{{if $i}};{{end}}{{ $dns }}{{end}}
{{- end }}

[ipv6]
{{- if .IPv6Address }}
method=manual
addresses={{ .IPv6Address }}
{{- if .IPv6Gateway }}
gateway={{ .IPv6Gateway }}
{{- end }}
{{- else }}
method=auto
{{- end }}`

	// 创建 bonding slave 接口
	bondSlaveInterface := types.Interface{
		Name: "ens36",
		MTU:  1500,
		BondingSlave: &types.BondingSlaveConfig{
			Enabled: true,
			Master:  "bond1",
		},
	}

	t.Run("Old Template (Without Bonding Support)", func(t *testing.T) {
		tmpl, err := template.New("old").Parse(oldTemplate)
		if err != nil {
			t.Fatalf("Failed to parse old template: %v", err)
		}

		var content strings.Builder
		if err := tmpl.Execute(&content, bondSlaveInterface); err != nil {
			t.Fatalf("Failed to execute old template: %v", err)
		}

		oldConfig := content.String()
		t.Logf("Old template output (incorrect for bonding slave):\n%s", oldConfig)

		// 验证旧模板的问题
		if strings.Contains(oldConfig, "master=") {
			t.Error("Old template incorrectly contains master configuration")
		}

		if strings.Contains(oldConfig, "slave-type=bond") {
			t.Error("Old template incorrectly contains slave-type=bond")
		}

		// 旧模板会错误地包含 IP 配置部分
		if !strings.Contains(oldConfig, "[ipv4]") {
			t.Log("Old template correctly excludes [ipv4] section (but this is accidental)")
		}
	})

	t.Run("New Template (With Bonding Support)", func(t *testing.T) {
		tmpl, err := template.New("new").Parse(nmConnectionTemplate)
		if err != nil {
			t.Fatalf("Failed to parse new template: %v", err)
		}

		var content strings.Builder
		if err := tmpl.Execute(&content, bondSlaveInterface); err != nil {
			t.Fatalf("Failed to execute new template: %v", err)
		}

		newConfig := content.String()
		t.Logf("New template output (correct for bonding slave):\n%s", newConfig)

		// 验证新模板的正确性
		if !strings.Contains(newConfig, "master=bond1") {
			t.Error("New template should contain master=bond1")
		}

		if !strings.Contains(newConfig, "slave-type=bond") {
			t.Error("New template should contain slave-type=bond")
		}

		// 新模板不应该包含 IP 配置部分（对于 bonding slave）
		if strings.Contains(newConfig, "[ipv4]") {
			t.Error("New template should not contain [ipv4] section for bonding slave")
		}

		if strings.Contains(newConfig, "[ipv6]") {
			t.Error("New template should not contain [ipv6] section for bonding slave")
		}
	})

	t.Log("Bonding slave configuration comparison test completed")
}