# This file is generated by nix-operator
# Manual changes will be overwritten
network:
  version: 2
  ethernets:
{{- range $name, $iface := .Ethernets }}
    {{ $name }}:
{{- if $iface.IPv4Address }}
      addresses:
        - {{ $iface.IPv4Address }}
{{- end }}
{{- if $iface.IPv6Address }}
        - {{ $iface.IPv6Address }}
{{- end }}
{{- if $iface.IPv4Gateway }}
      gateway4: {{ $iface.IPv4Gateway }}
{{- end }}
{{- if $iface.IPv6Gateway }}
      gateway6: {{ $iface.IPv6Gateway }}
{{- end }}
{{- if $iface.MTU }}
      mtu: {{ $iface.MTU }}
{{- end }}
{{- if $iface.Nameservers }}
      nameservers:
        addresses:
{{- range $iface.Nameservers }}
          - {{ . }}
{{- end }}
{{- end }}
{{- end }}