# Generated by nix-operator bond configuration
TYPE=Bond
BONDING_MASTER=yes
DEVICE={{.Name}}
NAME={{.Name}}
ONBOOT=yes
BONDING_OPTS="mode={{.Mode}} miimon={{.Miimon}}{{range $key, $value := .Options.ExtraOptions}} {{$key}}={{$value}}{{end}}"
{{- if .IPv4IP}}
BOOTPROTO=static
IPADDR={{.IPv4IP}}
{{- if .IPv4Netmask}}
NETMASK={{.IPv4Netmask}}
{{- end}}
{{- if .Network.Gateway}}
GATEWAY={{.Network.Gateway}}
{{- end}}
{{- if .Network.DNSServers}}
DNS1={{index .Network.DNSServers 0}}
{{- if gt (len .Network.DNSServers) 1}}
DNS2={{index .Network.DNSServers 1}}
{{- end}}
{{- end}}
{{- else}}
BOOTPROTO=dhcp
{{- end}}
{{- if .Network.MTU}}
MTU={{.Network.MTU}}
{{- end}}