# Generated by nix-operator
TYPE=Ethernet
PROXY_METHOD=none
BROWSER_ONLY=no
BOOTPROTO={{if .IPv4IP}}static{{else}}dhcp{{end}}
DEFROUTE=yes
IPV4_FAILURE_FATAL=no
IPV6INIT=yes
IPV6_AUTOCONF={{if .IPv6IP}}no{{else}}yes{{end}}
IPV6_DEFROUTE=yes
IPV6_FAILURE_FATAL=no
IPV6_ADDR_GEN_MODE=stable-privacy
NAME={{.Name}}
UUID={{.Name}}-nix-operator
DEVICE={{.Name}}
ONBOOT=yes
{{- if .IPv4IP}}
IPADDR={{.IPv4IP}}
{{- if .IPv4Netmask}}
NETMASK={{.IPv4Netmask}}
{{- end}}
{{- if .IPv4Gateway}}
GATEWAY={{.IPv4Gateway}}
{{- end}}
{{- if .Nameservers}}
DNS1={{index .Nameservers 0}}
{{- if gt (len .Nameservers) 1}}
DNS2={{index .Nameservers 1}}
{{- end}}
{{- if gt (len .Nameservers) 2}}
DNS3={{index .Nameservers 2}}
{{- end}}
{{- end}}
{{- end}}
{{- if .IPv6IP}}
{{- if .IPv6Prefix}}
IPV6ADDR={{.IPv6IP}}/{{.IPv6Prefix}}
{{- else}}
IPV6ADDR={{.IPv6IP}}
{{- end}}
{{- if .IPv6Gateway}}
IPV6_DEFAULTGW={{.IPv6Gateway}}
{{- end}}
{{- end}}
{{- if .MTU}}
MTU={{.MTU}}
{{- end}}