# This file is generated by nix-operator
# Manual changes will be overwritten

# The loopback network interface
auto lo
iface lo inet loopback

{{- range $name, $iface := .Interfaces }}
# Interface {{ $name }}
auto {{ $name }}
{{- if $iface.IPv4Address }}
iface {{ $name }} inet static
    address {{ $iface.IPv4Address }}
{{- if $iface.IPv4Gateway }}
    gateway {{ $iface.IPv4Gateway }}
{{- end }}
{{- if $iface.Nameservers }}
    dns-nameservers {{ range $i, $dns := $iface.Nameservers }}{{if $i}} {{end}}{{ $dns }}{{end}}
{{- end }}
{{- else }}
iface {{ $name }} inet dhcp
{{- end }}
{{- if $iface.MTU }}
    mtu {{ $iface.MTU }}
{{- end }}

{{- if $iface.IPv6Address }}
iface {{ $name }} inet6 static
    address {{ $iface.IPv6Address }}
{{- if $iface.IPv6Gateway }}
    gateway {{ $iface.IPv6Gateway }}
{{- end }}
{{- end }}
{{- end }}