# Generated by nix-operator for openEuler
network:
  version: 2
  renderer: networkd
  ethernets:
    {{.Name}}:
{{if .BondingSlave}}
{{if .BondingSlave.Enabled}}
      # Bond slave configuration - handled by bond master
{{else}}
{{if .IPv4Address}}
      addresses:
        - {{.IPv4Address}}
{{if .IPv4Gateway}}
      gateway4: {{.IPv4Gateway}}
{{end}}
{{end}}
{{if .IPv6Address}}
      addresses:
        - {{.IPv6Address}}
{{if .IPv6Gateway}}
      gateway6: {{.IPv6Gateway}}
{{end}}
{{end}}
{{if not .IPv4Address}}
      dhcp4: true
{{end}}
{{if not .IPv6Address}}
      dhcp6: true
{{end}}
{{if .Nameservers}}
      nameservers:
        addresses:
{{range .Nameservers}}
          - {{.}}
{{end}}
{{end}}
{{if .MTU}}
      mtu: {{.MTU}}
{{end}}
{{end}}
{{else}}
{{if .IPv4Address}}
      addresses:
        - {{.IPv4Address}}
{{if .IPv4Gateway}}
      gateway4: {{.IPv4Gateway}}
{{end}}
{{end}}
{{if .IPv6Address}}
      addresses:
        - {{.IPv6Address}}
{{if .IPv6Gateway}}
      gateway6: {{.IPv6Gateway}}
{{end}}
{{end}}
{{if not .IPv4Address}}
      dhcp4: true
{{end}}
{{if not .IPv6Address}}
      dhcp6: true
{{end}}
{{if .Nameservers}}
      nameservers:
        addresses:
{{range .Nameservers}}
          - {{.}}
{{end}}
{{end}}
{{if .MTU}}
      mtu: {{.MTU}}
{{end}}
{{end}}