# Generated by nix-operator for openEuler
# Interface: {{.Name}}
TYPE=Ethernet
PROXY_METHOD=none
BROWSER_ONLY=no
{{if .BondingSlave}}
{{if .BondingSlave.Enabled}}
# Bond slave configuration
SLAVE=yes
MASTER={{.BondingSlave.Master}}
BOOTPROTO=none
{{else}}
BOOTPROTO={{if .IPv4IP}}static{{else}}dhcp{{end}}
{{end}}
{{else}}
BOOTPROTO={{if .IPv4IP}}static{{else}}dhcp{{end}}
{{end}}
DEFROUTE=yes
IPV4_FAILURE_FATAL=no
{{if .IPv6IP}}
IPV6INIT=yes
IPV6_AUTOCONF=yes
IPV6_DEFROUTE=yes
IPV6_FAILURE_FATAL=no
IPV6_ADDR_GEN_MODE=stable-privacy
{{else}}
IPV6INIT=no
{{end}}
NAME={{.Name}}
UUID={{.Name}}-$(uuidgen)
DEVICE={{.Name}}
ONBOOT=yes
{{if and .IPv4IP (not (and .BondingSlave .BondingSlave.Enabled))}}
IPADDR={{.IPv4IP}}
{{if .IPv4Netmask}}
NETMASK={{.IPv4Netmask}}
{{end}}
{{if .IPv4Gateway}}
GATEWAY={{.IPv4Gateway}}
{{end}}
{{end}}
{{if and .IPv6IP (not (and .BondingSlave .BondingSlave.Enabled))}}
IPV6ADDR={{.IPv6IP}}
{{if .IPv6Prefix}}
IPV6PREFIX={{.IPv6Prefix}}
{{end}}
{{if .IPv6Gateway}}
IPV6_DEFAULTGW={{.IPv6Gateway}}
{{end}}
{{end}}
{{if .MTU}}
MTU={{.MTU}}
{{end}}
{{if and .Nameservers (not (and .BondingSlave .BondingSlave.Enabled))}}
{{range $index, $ns := .Nameservers}}
DNS{{add $index 1}}={{$ns}}
{{end}}
{{end}}