# Generated by nix-operator for openEuler
{{- if and .BondingSlave .BondingSlave.Enabled}}
[connection]
id=nix-operator-{{.Name}}
type=ethernet
interface-name={{.Name}}
autoconnect=true
autoconnect-priority=1
master={{.BondingSlave.Master}}
slave-type=bond

[ethernet]
{{- if .MTU}}
mtu={{.MTU}}
{{- end}}
{{- else}}
[connection]
id=nix-operator-{{.Name}}
type=ethernet
interface-name={{.Name}}
autoconnect=true
autoconnect-priority=1

[ethernet]
{{- if .MTU}}
mtu={{.MTU}}
{{- end}}

[ipv4]
{{- if .IPv4Address}}
method=manual
addresses={{.IPv4Address}}
{{- if .IPv4Gateway}}
gateway={{.IPv4Gateway}}
{{- end}}
{{- if .Nameservers}}
dns={{range $index, $ns := .Nameservers}}{{if $index}};{{end}}{{$ns}}{{end}}
{{- end}}
{{- else}}
method=auto
{{- if .Nameservers}}
dns={{range $index, $ns := .Nameservers}}{{if $index}};{{end}}{{$ns}}{{end}}
{{- end}}
{{- end}}

[ipv6]
{{- if .IPv6Address}}
method=manual
addresses={{.IPv6Address}}
{{- if .IPv6Gateway}}
gateway={{.IPv6Gateway}}
{{- end}}
{{- else}}
method=auto
{{- end}}

[proxy]
{{- end}}