# Generated by nix-operator for openEuler
[connection]
id=nix-operator-{{.Name}}
type=ethernet
interface-name={{.Name}}
autoconnect=true
autoconnect-priority=1
{{if .BondingSlave}}
{{if .BondingSlave.Enabled}}
# Bond slave configuration
slave-type=bond
master={{.BondingSlave.Master}}
{{end}}
{{end}}

[ethernet]
{{if .MTU}}
mtu={{.MTU}}
{{end}}

[ipv4]
{{if .IPv4Address}}
method=manual
addresses={{.IPv4Address}}
{{if .IPv4Gateway}}
gateway={{.IPv4Gateway}}
{{end}}
{{if .Nameservers}}
dns={{range $index, $ns := .Nameservers}}{{if $index}};{{end}}{{$ns}}{{end}}
{{end}}
{{else}}
method=auto
{{end}}

[ipv6]
{{if .IPv6Address}}
method=manual
addresses={{.IPv6Address}}
{{if .IPv6Gateway}}
gateway={{.IPv6Gateway}}
{{end}}
{{else}}
method=auto
{{end}}

[proxy]