# KylinOS Bond Interface Configuration for {{.Bond.Name}}
# Generated by nix-operator
# Template: kylinos_ifupdown.tpl

# Bond master configuration
auto {{.Bond.Name}}
{{if .IPv4Network}}
iface {{.Bond.Name}} inet static
    address {{.IPv4Network}}
    netmask {{.IPv4Netmask}}
{{if .Bond.IPv4Gateway}}    gateway {{.Bond.IPv4Gateway}}{{end}}
{{if .Bond.MTU}}    mtu {{.Bond.MTU}}{{end}}
{{if .Bond.Nameservers}}    dns-nameservers {{range $i, $ns := .Bond.Nameservers}}{{if $i}} {{end}}{{$ns}}{{end}}{{end}}
    # Bond specific options
    bond-mode {{.Bond.Mode}}
{{if .Bond.Miimon}}    bond-miimon {{.Bond.Miimon}}{{end}}
{{if .Bond.Slaves}}    bond-slaves {{range $i, $slave := .Bond.Slaves}}{{if $i}} {{end}}{{$slave}}{{end}}{{end}}
{{else}}
iface {{.Bond.Name}} inet dhcp
{{if .Bond.MTU}}    mtu {{.Bond.MTU}}{{end}}
    # Bond specific options
    bond-mode {{.Bond.Mode}}
{{if .Bond.Miimon}}    bond-miimon {{.Bond.Miimon}}{{end}}
{{if .Bond.Slaves}}    bond-slaves {{range $i, $slave := .Bond.Slaves}}{{if $i}} {{end}}{{$slave}}{{end}}{{end}}
{{end}}

{{if .IPv6Network}}
# IPv6 configuration
iface {{.Bond.Name}} inet6 static
    address {{.IPv6Network}}/{{.IPv6Prefix}}
{{if .Bond.IPv6Gateway}}    gateway {{.Bond.IPv6Gateway}}{{end}}
{{if .Bond.Nameservers}}    dns-nameservers {{range $i, $ns := .Bond.Nameservers}}{{if $i}} {{end}}{{$ns}}{{end}}{{end}}
{{end}}

# Bond interface hooks
post-up echo "KylinOS bond interface {{.Bond.Name}} configured via ifupdown" | logger -t nix-operator
post-down echo "KylinOS bond interface {{.Bond.Name}} brought down" | logger -t nix-operator