# KylinOS Bond Netplan Configuration for {{.Bond.Name}}
# Generated by nix-operator
# Template: kylinos_netplan.tpl

network:
  version: 2
  renderer: networkd
  bonds:
    {{.Bond.Name}}:
      interfaces:
{{range .Bond.Slaves}}        - {{.}}
{{end}}
      parameters:
        mode: {{.Bond.Mode}}
{{if .Bond.Miimon}}        mii-monitor-interval: {{.Bond.Miimon}}
{{end}}
{{if .Bond.MTU}}      mtu: {{.Bond.MTU}}
{{end}}
{{if or .IPv4Network .IPv6Network .Bond.IPv4Gateway .Bond.IPv6Gateway .Bond.Nameservers}}
      addresses:
{{if .IPv4Network}}        - {{.IPv4Network}}/{{.IPv4Prefix}}
{{end}}
{{if .IPv6Network}}        - {{.IPv6Network}}/{{.IPv6Prefix}}
{{end}}
{{if or .Bond.IPv4Gateway .Bond.IPv6Gateway}}
      routes:
{{if .Bond.IPv4Gateway}}        - to: 0.0.0.0/0
          via: {{.Bond.IPv4Gateway}}
{{end}}
{{if .Bond.IPv6Gateway}}        - to: ::/0
          via: {{.Bond.IPv6Gateway}}
{{end}}
{{end}}
{{if .Bond.Nameservers}}
      nameservers:
        addresses:
{{range .Bond.Nameservers}}          - {{.}}
{{end}}
{{end}}
{{else}}
      dhcp4: true
      dhcp6: true
{{end}}