# KylinOS NetworkManager Bond Configuration for {{.BondConfig.Name}}
# Generated by nix-operator
# Template: kylinos_bond_nmconnection.tpl

[connection]
id=nix-operator-bond-{{.BondConfig.Name}}
uuid={{generateUUID}}
type=bond
interface-name={{.BondConfig.Name}}
autoconnect=true

[bond]
mode={{.BondConfig.Mode}}
{{if .BondConfig.Miimon}}miimon={{.BondConfig.Miimon}}{{end}}
{{range $key, $value := .BondConfig.Options.ExtraOptions}}{{$key}}={{$value}}
{{end}}

[ipv4]
{{if .BondConfig.Network.IP}}
method=manual
{{$ipParts := splitCIDR .BondConfig.Network.IP}}addresses={{index $ipParts 0}}/{{index $ipParts 1}}
{{if .BondConfig.Network.Gateway}}gateway={{.BondConfig.Network.Gateway}}{{end}}
{{if .BondConfig.Network.DNSServers}}dns={{range $i, $ns := .BondConfig.Network.DNSServers}}{{if $i}};{{end}}{{$ns}}{{end}}{{end}}
{{else}}
method=auto
{{end}}

[ipv6]
method=auto

{{if .BondConfig.Network.MTU}}
[ethernet]
mtu={{.BondConfig.Network.MTU}}
{{end}}