# KylinOS Netplan Bond Configuration for {{.BondConfig.Name}}
# Generated by nix-operator
# Template: kylinos_bond_netplan.tpl

network:
  version: 2
  renderer: networkd
  bonds:
    {{.BondConfig.Name}}:
      parameters:
        mode: {{getBondModeString .BondConfig.Mode}}
{{if .BondConfig.Miimon}}        mii-monitor-interval: {{.BondConfig.Miimon}}
{{end}}{{range $key, $value := .BondConfig.Options.ExtraOptions}}        {{$key}}: {{$value}}
{{end}}{{if .BondConfig.Network.IP}}      addresses:
        - {{.BondConfig.Network.IP}}
{{end}}{{if .BondConfig.Network.Gateway}}      gateway4: {{.BondConfig.Network.Gateway}}
{{end}}{{if .BondConfig.Network.DNSServers}}      nameservers:
        addresses:
{{range .BondConfig.Network.DNSServers}}          - {{.}}
{{end}}{{end}}{{if .BondConfig.Network.MTU}}      mtu: {{.BondConfig.Network.MTU}}
{{end}}      dhcp4: {{if .BondConfig.Network.IP}}false{{else}}true{{end}}
      dhcp6: false