# KylinOS Bond NetworkManager Configuration for {{.Bond.Name}}
# Generated by nix-operator
# Template: kylinos_networkmanager.tpl

[connection]
id={{.Bond.Name}}
type=bond
interface-name={{.Bond.Name}}
autoconnect=true

[bond]
mode={{.Bond.Mode}}
{{if .Bond.Miimon}}miimon={{.Bond.Miimon}}{{end}}

[ipv4]
{{if .IPv4Network}}
method=manual
addresses={{.IPv4Network}}/{{.IPv4Prefix}}
{{if .Bond.IPv4Gateway}}gateway={{.Bond.IPv4Gateway}}{{end}}
{{if .Bond.Nameservers}}dns={{range $i, $ns := .Bond.Nameservers}}{{if $i}};{{end}}{{$ns}}{{end}}{{end}}
{{else}}
method=auto
{{end}}

{{if .IPv6Network}}
[ipv6]
method=manual
addresses={{.IPv6Network}}/{{.IPv6Prefix}}
{{if .Bond.IPv6Gateway}}gateway={{.Bond.IPv6Gateway}}{{end}}
{{if .Bond.Nameservers}}dns={{range $i, $ns := .Bond.Nameservers}}{{if $i}};{{end}}{{$ns}}{{end}}{{end}}
{{else}}
[ipv6]
method=auto
{{end}}

{{if .Bond.MTU}}
[ethernet]
mtu={{.Bond.MTU}}
{{end}}