# Generated by nix-operator. DO NOT EDIT.

# Host addresses
127.0.0.1	localhost
::1		localhost ip6-localhost ip6-loopback
ff02::1		ip6-allnodes
ff02::2		ip6-allrouters

# Custom hosts entries
{{range .Hosts}}{{.Ip}}	{{range $i, $h := .Hostnames}}{{if $i}} {{end}}{{$h}}{{end}}
{{end}}