# Generated by nix-operator. DO NOT EDIT.

# Host addresses
127.0.0.1   localhost localhost.localdomain localhost4 localhost4.localdomain4
::1         localhost localhost.localdomain localhost6 localhost6.localdomain6
ff02::1		ip6-allnodes
ff02::2		ip6-allrouters

# Custom hosts entries
{{range .Hosts}}{{.Ip}}	{{range $i, $h := .Hostnames}}{{if $i}} {{end}}{{$h}}{{end}}
{{end}}