# Generated by nix-operator for openEuler Bond interface {{.Name}}
# Bond专用虚拟网卡配置 - 只负责主接口
DEVICE={{.Name}}
TYPE=Bond
BONDING_MASTER=yes
ONBOOT=yes
BOOTPROTO={{if .IPv4IP}}static{{else}}dhcp{{end}}
DEFROUTE=yes
IPV4_FAILURE_FATAL=no
IPV6INIT=no
NAME={{.Name}}
UUID={{.Name}}-$(uuidgen)
{{if .IPv4IP}}
IPADDR={{.IPv4IP}}
{{if .IPv4Netmask}}
NETMASK={{.IPv4Netmask}}
{{end}}
{{if .IPv4Gateway}}
GATEWAY={{.IPv4Gateway}}
{{end}}
{{end}}
{{if .MTU}}
MTU={{.MTU}}
{{end}}
{{if .Nameservers}}
{{range $index, $ns := .Nameservers}}
DNS{{add $index 1}}={{$ns}}
{{end}}
{{end}}

# Bond specific options
BONDING_OPTS="mode={{.Mode}} miimon={{.Miimon}}"

# Additional openEuler specific settings
NM_CONTROLLED=no
USERCTL=no
PEERDNS=yes
PROXY_METHOD=none
BROWSER_ONLY=no