# KylinOS NetworkManager Connection Configuration for {{.Interface.Name}}
# Generated by nix-operator
# Template: kylinos_nmconnection.tpl

[connection]
id={{.Interface.Name}}
uuid={{.ConnectionUUID}}
type=ethernet
interface-name={{.Interface.Name}}
autoconnect=true
autoconnect-priority=1
{{if .HasBonding}}
slave-type=bond
master={{.Interface.BondingSlave.Master}}
{{end}}

[ethernet]
{{if .Interface.MTU}}
mtu={{.Interface.MTU}}
{{end}}

{{if not .HasBonding}}
{{if .HasIPv4}}
[ipv4]
method=manual
addresses={{.Interface.IPv4Address}}
{{if .Interface.IPv4Gateway}}gateway={{.Interface.IPv4Gateway}}{{end}}
{{if .DNSServers}}dns={{.DNSServers}}{{end}}
{{else}}
[ipv4]
method=auto
{{end}}

{{if .HasIPv6}}
[ipv6]
method=manual
addresses={{.Interface.IPv6Address}}
{{if .Interface.IPv6Gateway}}gateway={{.Interface.IPv6Gateway}}{{end}}
{{if .DNSServers}}dns={{.DNSServers}}{{end}}
{{else}}
[ipv6]
method=auto
{{end}}
{{else}}
# Bonding slave - no IP configuration
[ipv4]
method=disabled

[ipv6]
method=disabled
{{end}}

[proxy]
method=none