# KylinOS Network Interface Configuration for {{.Interface.Name}}
# Generated by nix-operator
# Template: kylinos_ifupdown.tpl

{{if .HasBonding}}
# Bonding slave configuration
auto {{.Interface.Name}}
iface {{.Interface.Name}} inet manual
    bond-master {{.Interface.BondingSlave.Master}}
    bond-primary {{.Interface.Name}}
{{else}}
# Standard interface configuration
auto {{.Interface.Name}}
{{if .IPv4Network}}
iface {{.Interface.Name}} inet static
    address {{.IPv4Network}}
    netmask {{.IPv4Netmask}}
{{if .Interface.IPv4Gateway}}    gateway {{.Interface.IPv4Gateway}}{{end}}
{{if .Interface.MTU}}    mtu {{.Interface.MTU}}{{end}}
{{if .Interface.Nameservers}}    dns-nameservers {{range $i, $ns := .Interface.Nameservers}}{{if $i}} {{end}}{{$ns}}{{end}}{{end}}
{{else}}
iface {{.Interface.Name}} inet dhcp
{{if .Interface.MTU}}    mtu {{.Interface.MTU}}{{end}}
{{end}}

{{if .IPv6Network}}
# IPv6 configuration
iface {{.Interface.Name}} inet6 static
    address {{.IPv6Network}}/{{.IPv6Prefix}}
{{if .Interface.IPv6Gateway}}    gateway {{.Interface.IPv6Gateway}}{{end}}
{{if .Interface.Nameservers}}    dns-nameservers {{range $i, $ns := .Interface.Nameservers}}{{if $i}} {{end}}{{$ns}}{{end}}{{end}}
{{end}}
{{end}}

# Interface bring up/down hooks
post-up echo "KylinOS interface {{.Interface.Name}} configured via ifupdown" | logger -t nix-operator
post-down echo "KylinOS interface {{.Interface.Name}} brought down" | logger -t nix-operator