# KylinOS Netplan Network Configuration for {{.Interface.Name}}
# Generated by nix-operator
# Template: kylinos_netplan.tpl

network:
  version: 2
  renderer: {{.Renderer}}
  ethernets:
    {{.Interface.Name}}:
{{if .HasBonding}}
      # Bonding slave configuration
      dhcp4: false
      dhcp6: false
{{else}}
      # Standard interface configuration
{{if .HasIPv4}}
      dhcp4: false
      addresses:
        - {{.Interface.IPv4Address}}
{{if .Interface.IPv4Gateway}}
      gateway4: {{.Interface.IPv4Gateway}}
{{end}}
{{else}}
      dhcp4: true
{{end}}
{{if .HasIPv6}}
      dhcp6: false
      addresses:
        - {{.Interface.IPv6Address}}
{{if .Interface.IPv6Gateway}}
      gateway6: {{.Interface.IPv6Gateway}}
{{end}}
{{else}}
      dhcp6: true
{{end}}
{{if .DNSServers}}
      nameservers:
        addresses:
{{range .DNSServers}}
          - {{.}}
{{end}}
{{end}}
{{end}}
{{if .Interface.MTU}}
      mtu: {{.Interface.MTU}}
{{end}}
{{if .HasBonding}}
  bonds:
    {{.Interface.BondingSlave.Master}}:
      interfaces:
        - {{.Interface.Name}}
      parameters:
        mode: active-backup
        primary: {{.Interface.Name}}
        mii-monitor-interval: 100
{{if .HasIPv4}}
      dhcp4: false
      addresses:
        - {{.Interface.IPv4Address}}
{{if .Interface.IPv4Gateway}}
      gateway4: {{.Interface.IPv4Gateway}}
{{end}}
{{else}}
      dhcp4: true
{{end}}
{{if .HasIPv6}}
      dhcp6: false
      addresses:
        - {{.Interface.IPv6Address}}
{{if .Interface.IPv6Gateway}}
      gateway6: {{.Interface.IPv6Gateway}}
{{end}}
{{else}}
      dhcp6: true
{{end}}
{{if .DNSServers}}
      nameservers:
        addresses:
{{range .DNSServers}}
          - {{.}}
{{end}}
{{end}}
{{end}}