# Generated by nix-operator for KylinOS
{{- if and .Interface.BondingSlave .Interface.BondingSlave.Enabled}}
[connection]
id=nix-operator-{{.Interface.Name}}
type=ethernet
interface-name={{.Interface.Name}}
autoconnect=true
autoconnect-priority=1
master={{.Interface.BondingSlave.Master}}
slave-type=bond

[ethernet]
{{- if .Interface.MTU}}
mtu={{.Interface.MTU}}
{{- end}}
{{- else}}
[connection]
id=nix-operator-{{.Interface.Name}}
type=ethernet
interface-name={{.Interface.Name}}
autoconnect=true
autoconnect-priority=1

[ethernet]
{{- if .Interface.MTU}}
mtu={{.Interface.MTU}}
{{- end}}

[ipv4]
{{- if .Interface.IPv4Address}}
method=manual
addresses={{.Interface.IPv4Address}}
{{- if .Interface.IPv4Gateway}}
gateway={{.Interface.IPv4Gateway}}
{{- end}}
{{- if .Interface.Nameservers}}
dns={{range $index, $ns := .Interface.Nameservers}}{{if $index}};{{end}}{{$ns}}{{end}}
{{- end}}
{{- else}}
method=auto
{{- if .Interface.Nameservers}}
dns={{range $index, $ns := .Interface.Nameservers}}{{if $index}};{{end}}{{$ns}}{{end}}
{{- end}}
{{- end}}

[ipv6]
{{- if .Interface.IPv6Address}}
method=manual
addresses={{.Interface.IPv6Address}}
{{- if .Interface.IPv6Gateway}}
gateway={{.Interface.IPv6Gateway}}
{{- end}}
{{- else}}
method=auto
{{- end}}

[proxy]
method=none
{{- end}}